#!/usr/bin/env node

var source = '';

process.stdin.resume();

process.stdin.on('data', function (d) {
  source += d.toString();
});

process.stdin.on('end', function () {
  console.log(require('./index').process(source));
});
